import type { Email } from './email';

/**
 * Aggregate root for the Identity bounded context (docs/architecture/domain-boundaries.md).
 * See docs/architecture/ddd-tactical-design.md — named `Account`, not `User`,
 * decided before any code depended on the old name.
 */
export class Account {
  private constructor(
    readonly id: string,
    private readonly email: Email,
    private readonly passwordHash: string,
    readonly createdAt: Date,
    readonly updatedAt: Date,
  ) {}

  /** A brand-new account, not yet persisted. `id` is generated by the repository on insert. */
  static register(params: { id: string; email: Email; passwordHash: string; now: Date }): Account {
    return new Account(params.id, params.email, params.passwordHash, params.now, params.now);
  }

  /** Rebuilds an Account from persisted state — never validates business rules, only shape. */
  static reconstitute(params: {
    id: string;
    email: Email;
    passwordHash: string;
    createdAt: Date;
    updatedAt: Date;
  }): Account {
    return new Account(params.id, params.email, params.passwordHash, params.createdAt, params.updatedAt);
  }

  getEmail(): Email {
    return this.email;
  }

  getPasswordHash(): string {
    return this.passwordHash;
  }
}
